modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
credits="Iron431 for Iron's Spells 'n Spellbooks"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.weaving_infinity]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.weaving_infinity]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.weaving_infinity]]
    modId="irons_spellbooks"
    type="required"
    versionRange="[${irons_spellbooks_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.weaving_infinity]]
    modId="curios"
    type="required"
    versionRange="[9.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.weaving_infinity]]
    modId="geckolib"
    type="required"
    versionRange="[4.7.0,)"
    ordering="AFTER"
    side="BOTH"
